name: Bug
description: File a bug found in Chaos.
labels: ['bug', 'triage']
assignees:
  - beauchama
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please fill in the information below to help us reproduce the issue you are experiencing.
        Make sure to search if the issue has already been reported ([chaos/issues](https://github.com/wavepulse/chaos/issues)) before submitting a new one.
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Please provide a detailed description of the bug you are experiencing.
      placeholder: The window does not close when clicking the close button.
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Is there anything else you would like to add such as links, references? Anything that might help us debug the issue.
        Tip: You can drag and drop images, videos, and other files into this text box.
